<<<<<<< HEAD
name: Add Reviewers

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Reviewers to PR"
      uses: itsOliverBott/assign-pr-reviewers@release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        users: "michl1001, derek-hwang27" # comma-separated (example: "itsOliverBott, SantaClaus, b4tman, sp0derman")
=======
name: Add Reviewers

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Reviewers to PR"
      uses: itsOliverBott/assign-pr-reviewers@release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        users: "michl1001, derek-hwang27" # comma-separated (example: "itsOliverBott, SantaClaus, b4tman, sp0derman")
>>>>>>> 5ec17a4ae881fc58b549800f38684cba4d782d59
        ignore-drafts: true # defaults to false if not provided